# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-09 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_messages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='receiver_user',
        ),
    ]
