# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-09-13 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user_messages', '0002_remove_message_receiver_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroomaggregator',
            name='user',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='check',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='message_aggregator',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='total_messages',
        ),
        migrations.RemoveField(
            model_name='chatroom',
            name='unchecked_messages',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='ChatRoomAggregator',
        ),
    ]
